#!/usr/bin/env python
# -*- coding: utf-8 -*-

import SCons.Script
import os

base_dir = os.path.join('..', '..')
lib_dir = os.path.join(base_dir, 'lib')
include_dir = os.path.join(base_dir, 'include')

env = Environment(CCFLAGS='-lm', LIBPATH=lib_dir, CPPPATH=include_dir)
# LibraryやExecuteはみなSCons.Script.SConscript.DefaultEnvironmentCall 
env.Library(os.path.join(lib_dir, 'hfsecurity'), ['encrypt.c', 'checksum.c'])
Install(include_dir,  ['encrypt.h', 'checksum.h'])
env.Program('static', 'static.c', LIBS=['hfsecurity'])

